"""
Packs the web UI (web/) gzipped into src/web_assets.h.

index.html is bundled into ONE self-contained page: stylesheets, scripts and
the favicon are inlined. The ESP32's web server handles one connection at a
time, so a single request loads much faster and more reliably on phones
(iOS Safari otherwise opens several parallel connections).

Runs automatically before every PlatformIO build (extra_scripts = pre:...)
and can also be run by hand:  python tools/embed_web.py
The header is only rewritten when the content changed.
"""
import base64
import gzip
import hashlib
import os
import re

try:
    Import("env")  # noqa: F821  (PlatformIO / SCons)
    ROOT = env.subst("$PROJECT_DIR")  # noqa: F821
except NameError:
    ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# URL path, file below web/, MIME type.  Entry 0 must be "/" (bundled index).
ASSETS = [
    ("/",             "index.html",           "text/html; charset=utf-8"),
]


def bundle(web):
    """index.html with every local <link>/<script src> inlined."""
    def read(rel):
        # the page references "xterm.js" etc.; third-party files live in web/vendor/
        for cand in (os.path.join(web, rel), os.path.join(web, "vendor", rel)):
            if os.path.exists(cand):
                with open(cand, "r", encoding="utf-8") as f:
                    return f.read()
        raise SystemExit("embed_web: %s not found in web/ or web/vendor/" % rel)

    html = read("index.html")

    def css(m):
        body = read(m.group(1))
        if re.search(r"</style", body, re.I):
            raise SystemExit("embed_web: %s contains </style" % m.group(1))
        return "<style>\n%s\n</style>" % body

    def js(m):
        body = re.sub(r"//# sourceMappingURL=\S+", "", read(m.group(1)))
        if re.search(r"</script|<!--", body, re.I):
            raise SystemExit("embed_web: %s cannot be inlined safely" % m.group(1))
        return "<script>\n%s\n</script>" % body

    def icon(m):
        data = base64.b64encode(read(m.group(1)).encode()).decode()
        return '<link rel="icon" href="data:image/svg+xml;base64,%s">' % data

    html = re.sub(r'<link rel="icon" href="([^":]+)"[^>]*>', icon, html)
    html = re.sub(r'<link rel="stylesheet" href="([^":]+)">', css, html)
    html = re.sub(r'<script src="([^":]+)"></script>', js, html)
    if re.search(r'(href|src)="(?!data:|https?:|#)[^"]+\.(css|js|svg)"', html):
        raise SystemExit("embed_web: unbundled reference left in index.html")
    return html.encode("utf-8")


def build():
    web = os.path.join(ROOT, "web")
    out_path = os.path.join(ROOT, "src", "web_assets.h")
    lines = [
        "// AUTO-GENERATED by tools/embed_web.py from web/ - do not edit",
        "#pragma once",
        "#include <Arduino.h>",
        "",
        "struct WebAsset { const char *path; const char *mime; const char *etag; const uint8_t *data; size_t len; };",
        "",
    ]
    table = []
    total = 0
    for i, (url, rel, mime) in enumerate(ASSETS):
        if rel == "index.html":
            raw = bundle(web)
        else:
            with open(os.path.join(web, rel), "rb") as f:
                raw = f.read()
        gz = gzip.compress(raw, compresslevel=9, mtime=0)
        total += len(gz)
        etag = hashlib.sha1(gz).hexdigest()[:12]
        lines.append("// %s%s (%d -> %d bytes)" % (rel, " (bundled)" if rel == "index.html" else "", len(raw), len(gz)))
        lines.append("static const uint8_t WA_%d[] PROGMEM = {" % i)
        for off in range(0, len(gz), 24):
            lines.append("  " + ",".join("0x%02x" % b for b in gz[off:off + 24]) + ",")
        lines.append("};")
        # ETag value includes the quotes: "abc123"
        table.append('  {"%s", "%s", "\\"%s\\"", WA_%d, sizeof(WA_%d)},' % (url, mime, etag, i, i))
    lines.append("")
    lines.append("static const WebAsset WEB_ASSETS[] = {")
    lines.extend(table)
    lines.append("};")
    lines.append("static const size_t WEB_ASSETS_COUNT = %d;" % len(ASSETS))
    lines.append("")
    content = "\n".join(lines)

    old = None
    if os.path.exists(out_path):
        with open(out_path, "r") as f:
            old = f.read()
    if old != content:
        with open(out_path, "w") as f:
            f.write(content)
        print("embed_web: wrote src/web_assets.h (%d bytes gzipped)" % total)
    else:
        print("embed_web: web assets unchanged")


build()
